### ISSUE TITLE
Issue while running ./get_qnas "<text>"

### ISSUE THREAD

**Issue by prakritidev** [deepmipt/question_generation#22]
Hi, 

I was trying this project on my docker. I am able to successfully install dependency of this project using `./setup` Everything is running on my docker and all containers are up and running. However, I encounter an error while trying using `./get_qnas` Below is the error stack.

`----------------Test output----------------
Waiting had its world premiere at the   Dubai International Film Festival on 11 December 2015 to positive reviews   from critics. It was also screened at the closing gala of the London Asian   Film Festival, where Menon won the Best Director Award.
Traceback (most recent call last):
  File "convert_text_to_opennmt_format.py", line 120, in <module>
    main(text)
  File "convert_text_to_opennmt_format.py", line 106, in main
    output =json.loads(output, encoding='utf-8', strict=False)
  File "/Users/prakritidevvema/anaconda3/envs/rk/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/Users/prakritidevvema/anaconda3/envs/rk/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/prakritidevvema/anaconda3/envs/rk/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
----------------Stopping containers----------------
corenlp
corenlp
opennmt
opennmt
` 

Did anyone encounter this issue? Or is it me who did something wrong. 

Thanks

**Comment by ant28** [comment]
Did you fix your problem? I encountered a similar error. When I tried the project, it didn't output anything.

**Comment by prakritidev** [comment]
No, I did not. Found a new project on github, but that was also not good enough. No updates on this issue from my side.

**Comment by gevarsovia** [comment]
I have got the same problem.
I discovery that I was having problem intalling the requirements. 

pycorenlp==0.3.0
pyzmq==16.0.2

It's called in this part of the setup file. 

echo "----------------Installing python requirements----------------"
pip3 install -r requirements.txt

For me it was a problem with the pip.
I just reinstalled it and it worked well.

**Comment by prakritidev** [comment]
Thanks, I'll try this on my end as well .

**Comment by IamGauravS** [comment]
> I have got the same problem.
> I discovery that I was having problem intalling the requirements.
> 
> pycorenlp==0.3.0
> pyzmq==16.0.2
> 
> It's called in this part of the setup file.
> 
> echo "----------------Installing python requirements----------------"
> pip3 install -r requirements.txt
> 
> For me it was a problem with the pip.
> I just reinstalled it and it worked well.

Were you able to run this?
